<?xml version="1.0" encoding="ISO-8859-1"?>
<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.1 Transitional//EN" "https://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="https://www.w3.org/1999/xhtml" lang="nl">
<head><meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" /><script type="text/javascript" src="incl/all.js"></script>
<link rel="stylesheet" type="text/css" href="css/2.css" /><title>Topics (1-15)</title>
</head><body><table align="center" border="0" width="640"><tr><td class="s">
</td><td class="s" align="right">
</td></tr><tr><td colspan="2">
<table width="100%" border="0" cellpadding="0" cellspacing="0"><tr><td class="q">
<table width="100%" border="0" cellspacing="1" cellpadding="5">
<tr class="c"><td colspan="5"><table width="100%" cellpadding="2" cellspacing="0"><tr><td nowrap="nowrap"><span class="c"><a href="main.php" id="lnk" title="Klik hier om de laatste topics te zien..." style="color:#ffffff;text-decoration:none" onmouseover="start_impress();return true" onmouseout="stop_impress();return true" onclick="refresh(0);return false">HUTTEN.BE FORUM</a></span></td><td align="right" nowrap="nowrap"><b><a href="new.php?f=0" style="color:#ffffff">Nieuw Topic</a></b></td></tr></table></td></tr>
<tr class="z"><td class="f" width="70%" nowrap="nowrap">&nbsp;Topics&nbsp;</td><td class="f" width="10%" nowrap="nowrap">&nbsp;Auteur&nbsp;</td><td class="f" width="10%" nowrap="nowrap">&nbsp;Laatste toevoeging&nbsp;</td><td class="f" width="5%" nowrap="nowrap">&nbsp;Reacties&nbsp;</td><td class="f" width="5%" nowrap="nowrap">&nbsp;Gelezen&nbsp;</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20050401073751&amp;u=3" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>avocet hoogtemeter</b></a><div class="s">In de jaren 90 kocht ik bij basecamp in nijlen een hoogtemeter "avocet".een toch...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />leo</b></td><td class="s" nowrap="nowrap">06 Apr 2005 15:45</td><td class="s">3</td><td class="s">33</td></tr>
<tr class="b"><td><a href="show.php?f=0&amp;topic=20050308133109&amp;u=5" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>zomervakantie in Mayrhofen</b></a><div class="s">Wij hebben een zomervakantie geboekt in Mayrhofen, hotel Berghof en hopen er moo...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />Hilde</b></td><td class="s" nowrap="nowrap">05 Apr 2005 13:44</td><td class="s">5</td><td class="s">187</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20050403205901&amp;u=1" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Klimpartner(s) gezocht</b></a><div class="s">Mijn klimpartner en ik zoeken nog 1 á 2 klimpartner(s) voor een reeks alpiene be...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />DDS</b></td><td class="s" nowrap="nowrap">03 Apr 2005 18:59</td><td class="s">1</td><td class="s">91</td></tr>
<tr class="b"><td><a href="show.php?f=0&amp;topic=20050330220151&amp;u=5" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>rudolfshutte in oostenrijk</b></a><div class="s">hé, kan er mij iemand info geven over de rudolfshutte en is het te doen met een ...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />sportie</b></td><td class="s" nowrap="nowrap">03 Apr 2005 10:10</td><td class="s">5</td><td class="s">112</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20050331174811&amp;u=2" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>beginner</b></a><div class="s">Beste huttengebruikers, Wij zijn absolute beginners. We hebben een hotelletje ge...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />Jan</b></td><td class="s" nowrap="nowrap">01 Apr 2005 07:28</td><td class="s">2</td><td class="s">116</td></tr>
<tr class="b"><td><a href="show.php?f=0&amp;topic=20050325152230&amp;u=3" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Naar de traquit in juni</b></a><div class="s">Ik zou in juni naar de traquit willen gaan,maar lees op deze site dat de hut dan...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />leo</b></td><td class="s" nowrap="nowrap">30 Mar 2005 12:59</td><td class="s">3</td><td class="s">98</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20050329133226&amp;u=2" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>wandelen laatste week mei, Zwitserland</b></a><div class="s">Beste mensen,  zijn er gebieden die aan te raden zijn voor de periode einde mei ...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />Mark Roosen</b></td><td class="s" nowrap="nowrap">29 Mar 2005 12:01</td><td class="s">2</td><td class="s">32</td></tr>
<tr class="b"><td><a href="show.php?f=0&amp;topic=20050328214715&amp;u=1" class="v"><img src="pics/t5.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>van Rif. Tommaso Perdotti naar Rif. Brentei</b></a><div class="s">Vraagje, weet iemand of het mogelijk is om vanaf de Rif. Tommaso Perdotti  naar ...</div></td>
<td nowrap="nowrap"><b><img src="pics/w5.gif" width="11" height="14" alt="" border="0" hspace="2" />Remco Jacobs</b></td><td class="s" nowrap="nowrap">28 Mar 2005 19:47</td><td class="s">1</td><td class="s">44</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20050307175753&amp;u=8" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Mer de glace (mont blanc)</b></a><div class="s">iemand ervaring met een toppoging via de mer de glace...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />grrr</b></td><td class="s" nowrap="nowrap">25 Mar 2005 07:50</td><td class="s">8</td><td class="s">213</td></tr>
<tr class="b"><td><a href="show.php?f=0&amp;topic=20050313115146&amp;u=7" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Gezekerd of niet gezekerd?</b></a><div class="s">Naar aanleiding van het artikel over de Oostenrijker en extreem klimmer: Koidl d...</div></td>
<td nowrap="nowrap"><b><a class="j" href="#" onclick="usr('joris');return false"><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />Joris</a></b></td><td class="s" nowrap="nowrap">24 Mar 2005 16:19</td><td class="s">7</td><td class="s">303</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20041010200327&amp;u=15" class="v"><img src="pics/t6.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Zwitserland of Oostenrijk?</b></a><div class="s">Hallo hallo,  Ik zit met een klein probleempje. Ik ben van plan om komende zomer...</div></td>
<td nowrap="nowrap"><b><img src="pics/s6.gif" width="11" height="14" alt="" border="0" hspace="2" />Swissgirl</b></td><td class="s" nowrap="nowrap">20 Mar 2005 18:54</td><td class="s">15</td><td class="s">701</td></tr>
<tr class="b"><td><a href="show.php?f=0&amp;topic=20050315145408&amp;u=8" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Pas de chèvre - Arolla</b></a><div class="s">Hallo,   Dit jaar ga ik weerom op vakantie richting Val d'Hérens. Vroeger (zo'n ...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />Tom</b></td><td class="s" nowrap="nowrap">17 Mar 2005 11:29</td><td class="s">8</td><td class="s">92</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20050306205938&amp;u=5" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>hutten in zwitserland</b></a><div class="s">Hey,  Dit jaar ga ik de haute route van Chamonix naar Zermatt lopen. iK slaap in...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />danny</b></td><td class="s" nowrap="nowrap">16 Mar 2005 19:36</td><td class="s">5</td><td class="s">90</td></tr>
<tr class="b"><td><a href="show.php?f=0&amp;topic=20050314175737&amp;u=2" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Prijs overnachting hutten en prijs consumpties</b></a><div class="s">Joris, is het mogelijk bij de hutten ook de prijzen van overnachting bij  te ver...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />F</b></td><td class="s" nowrap="nowrap">14 Mar 2005 19:33</td><td class="s">2</td><td class="s">76</td></tr>
<tr class="a"><td><a href="show.php?f=0&amp;topic=20050309233202&amp;u=3" class="v"><img src="pics/t1.gif" width="19" height="24" alt="" border="0" align="left" vspace="0" /><b>Grossglockner</b></a><div class="s">We willen met enkele vaders en hun kids een tocht in de streek rond de Grossgloc...</div></td>
<td nowrap="nowrap"><b><img src="pics/w1.gif" width="11" height="14" alt="" border="0" hspace="2" />Mvds</b></td><td class="s" nowrap="nowrap">13 Mar 2005 10:57</td><td class="s">3</td><td class="s">258</td></tr>
<tr class="b"><td class="f">&nbsp;<a href="new.php?f=0">Nieuw Topic</a></td><td align="center" nowrap="nowrap"><a href="#" onclick="zz=window.open('join.php','join','width=310,height=300,resizable=1');zz.focus();return false" title="Nieuw lid"><img src="pics/log.gif" width="24" border="0" height="14" hspace="3" alt="Nieuw lid" /></a> <a href="#" onclick="zz=window.open('log.php?f=0','log','width=310,height=300,resizable=1');zz.focus();return false" title="Login"><img src="pics/otb.gif" border="0" width="22" height="13" hspace="3" alt="Login" /></a></td><td align="center"><table cellpadding="0" cellspacing="0" width="100%"><tr><td align="center"><a href="main.php?f=0&amp;go=0" title="&lt;&lt;"><img src="pics/la.png" width="10" height="9" hspace="0" vspace="0" border="0" alt="&lt;&lt;" onmouseover="this.src='pics/lb.png'" onmouseout="this.src='pics/la.png'" /></a><img src="pics/on.png" width="10" height="9" hspace="1" vspace="0" alt="" /><a href="main.php?f=0&amp;go=15" title="Topics: 16-30"><img src="pics/of.png" width="10" height="9" hspace="0" vspace="0" border="0" alt="Topics: 16-30" onmouseover="this.src='pics/ou.png'" onmouseout="this.src='pics/of.png'" /></a><a href="main.php?f=0&amp;go=30" title="Topics: 31-45"><img src="pics/of.png" width="10" height="9" hspace="1" vspace="0" border="0" alt="Topics: 31-45" onmouseover="this.src='pics/ou.png'" onmouseout="this.src='pics/of.png'" /></a><a href="main.php?f=0&amp;go=45" title="Topics: 46-60"><img src="pics/of.png" width="10" height="9" hspace="0" vspace="0" border="0" alt="Topics: 46-60" onmouseover="this.src='pics/ou.png'" onmouseout="this.src='pics/of.png'" /></a><a href="main.php?f=0&amp;go=60" title="Topics: 61-75"><img src="pics/of.png" width="10" height="9" hspace="1" vspace="0" border="0" alt="Topics: 61-75" onmouseover="this.src='pics/ou.png'" onmouseout="this.src='pics/of.png'" /></a><a href="main.php?f=0&amp;go=15" title="&gt;&gt;"><img src="pics/ra.png" width="10" height="9" hspace="0" vspace="0" border="0" alt="&gt;&gt;" onmouseover="this.src='pics/rb.png'" onmouseout="this.src='pics/ra.png'" /></a></td><td>&nbsp;<a href="search.php?f=0"><img src="pics/find.gif" width="15" height="15" border="0" alt="Zoeken" title="Zoeken" /></a></td></tr></table></td><td align="center"><a href="admin.php?f=0" title="ADMIN" target="_blank"><img src="pics/adm.gif" width="14" height="12" border="0" alt="ADMIN" /></a></td><td align="center" class="f"><a href="#" style="text-decoration:none" onclick="yy=window.open('offset.php?f=0','offs','width=220,height=400,resizable=1');yy.focus();return false" title="Uw plaatselijke tijd">17:51</a></td></tr></table></td></tr></table>
<img align="right" border="0" vspace="2" hspace="0" src="pics/clr.gif" width="109" height="10" usemap="#clr" alt="Kleuren wijzigen..." /><map name="clr" id="clr"><area shape="rect" onclick="change_color(0,0);return false" coords="0,1,10,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,1);return false" coords="11,1,21,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,2);return false" coords="22,1,32,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,3);return false" coords="33,1,43,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,4);return false" coords="44,1,54,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,5);return false" coords="55,1,65,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,6);return false" coords="66,1,76,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,7);return false" coords="77,1,87,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,8);return false" coords="88,1,98,10" href="#" alt="Kleuren wijzigen..." /><area shape="rect" onclick="change_color(0,9);return false" coords="99,1,109,10" href="#" alt="Kleuren wijzigen..." /></map> 
<a href="info.php" onclick="uri=escape(window.location.toString());uri='info.php?uri='+uri;window.open(uri,'inf','width=250,height=125');return false" title="about EasyForum!"><img src="pics/ef.gif" width="14" height="12" vspace="0" hspace="1" border="0" align="left" alt="about EasyForum!" /></a>
<span class="f">0.024&nbsp;sec</span><br clear="all" />
</td></tr></table></body></html>
